name: FouziTagsUI
main: Fouzi\Tags\Main
version: 1.0.0
api: [3.0.0, 4.0.0]
website: https://www.github.com/iiFouzi
author: iiFouzi

commands:
  tags:
   description: "open TagsUI by iiFouzi"
   default: true